const jobRoles = {
  Sales: [
    "Sales Associate",
    "Sales Representative",
    "Sales Consultant",
    "Account Executive",
    "Inside Sales Representative",
    "Outside Sales Representative",
    "Sales Manager",
    "Regional Sales Manager",
    "National Sales Manager",
    "International Sales Manager",
    "Sales Director",
    "Vice President of Sales",
    "Chief Sales Officer",
    "Pharmaceutical Sales Representative",
    "Medical Device Sales Representative",
    "Software Sales Professional",
    "Automotive Sales Manager",
    "Real Estate Sales Agent",
    "Retail Sales Worker",
    "B2B Sales Specialist",
    "B2C Sales Specialist",
    "Technical Sales Engineer",
    "IT Sales Professional",
    "Advertising Sales Agent",
    "Financial Services Sales Agent",
    "Wholesale and Manufacturing Sales Representative",
    "Solutions Architect",
    "Pre-Sales Consultant",
    "Sales Engineer",
    "Channel Sales Specialist",
    "Sales Operations Manager",
    "Customer Success Manager",
    "Enterprise Sales Professional",
    "Key Account Manager",
    "Business Development Representative",
    "Sales Enablement Professional",
    "E-commerce Sales Strategist",
    "Sales Training Specialist",
    "Sales Analyst",
    "Sales Data Scientist",
    "Strategic Accounts Manager",
    "Global Accounts Manager",
    "Commercial Director",
    "Business Unit Director",
    "Market Development Manager",
    "Sales Negotiator",
    "Sales Liaison",
    "Partnership Director",
    "Sales Strategy Consultant",
  ],
  Marketing: [
    "Marketing Coordinator",
    "Marketing Manager",
    "Content Creator",
    "SEO Specialist",
    "Digital Marketing Manager",
    "Social Media Manager",
    "Brand Manager",
    "Product Marketing Manager",
    "Marketing Analyst",
    "Chief Marketing Officer",
    "Public Relations Specialist",
    "Marketing Consultant",
    "Advertising Manager",
    "Market Research Analyst",
    "Media Planner",
    "Event Planner",
    "Graphic Designer",
    "Copywriter",
    "Email Marketing Specialist",
    "Influencer Marketing Specialist",
    "Performance Marketer",
    "Web Content Specialist",
    "Digital Campaign Manager",
    "CRM Manager",
    "Affiliate Marketing Manager",
    "E-commerce Marketing Specialist",
    "Video Producer",
    "Visual Merchandiser",
    "PPC Specialist",
    "Brand Strategist",
    "Content Marketing Manager",
    "UX/UI Designer",
    "Data Analyst",
    "Marketing Technologist",
    "Customer Insight Manager",
    "Community Manager",
    "Marketing Automation Specialist",
    "B2B Marketing Specialist",
    "B2C Marketing Specialist",
    "Director of Marketing",
    "Vice President of Marketing",
    "Growth Hacker",
  ],
  CustomerService: [
    "Customer Service Representative",
    "Call Center Agent",
    "Customer Support Specialist",
    "Technical Support Specialist",
    "Client Relations Manager",
    "Help Desk Technician",
    "Customer Service Manager",
    "Service Advisor",
    "Account Manager",
    "Customer Experience Manager",
    "Customer Service Associate",
    "Live Chat Agent",
    "Customer Care Specialist",
    "Customer Relations Officer",
    "Client Services Coordinator",
    "Client Success Manager",
    "Service Delivery Manager",
    "Customer Service Analyst",
    "Support Engineer",
    "Customer Service Trainer",
    "Customer Loyalty Specialist",
    "Customer Outreach Coordinator",
    "Customer Retention Specialist",
    "Customer Service Team Lead",
    "Director of Customer Service",
    "Vice President of Customer Experience",
    "Customer Service Operations Manager",
    "Customer Engagement Specialist",
    "Customer Service Quality Auditor",
    "Complaints Manager",
    "Billing Support Specialist",
    "Support Services Administrator",
  ],
  BusinessDevelopment: [
    "Business Development Manager",
    "Business Development Executive",
    "Business Analyst",
    "Partnership Manager",
    "Strategic Planner",
    "Project Manager",
    "Corporate Strategy Manager",
    "Business Development Consultant",
    "Innovation Manager",
    "Commercial Director",
    "Relationship Manager",
    "Account Manager",
    "Sales Development Rep",
    "Business Development Associate",
    "Director of Business Development",
    "Vice President of Business Development",
    "International Business Development Manager",
    "Market Expansion Manager",
    "Client Services Director",
    "Merger and Acquisition Manager",
    "Franchise Development Manager",
    "Lead Generation Specialist",
    "Proposal Manager",
    "Strategic Alliances Manager",
    "Business Development Coordinator",
    "Business Operations Manager",
    "Business Development Analyst",
    "Product Manager",
    "Brand Development Manager",
    "New Business Coordinator",
    "Channel Development Manager",
  ],
  Engineering: [
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Software Engineer",
    "Chemical Engineer",
    "Systems Engineer",
    "Project Engineer",
    "Quality Assurance Engineer",
    "Operations Engineer",
    "Chief Engineer",
    "Biomedical Engineer",
    "Environmental Engineer",
    "Aerospace Engineer",
    "Network Engineer",
    "Computer Engineer",
    "Structural Engineer",
    "Process Engineer",
    "Industrial Engineer",
    "Maintenance Engineer",
    "Material Science Engineer",
    "Geo technical Engineer",
    "Automotive Engineer",
    "Marine Engineer",
    "Railway Engineer",
    "Telecommunications Engineer",
    "Data Engineer",
    "Security Engineer",
    "Petroleum Engineer",
    "Mining Engineer",
    "Hardware Engineer",
    "Firmware Engineer",
    "Acoustic Engineer",
    "Naval Architect",
    "Nuclear Engineer",
    "Robotics Engineer",
    "Field Engineer",
    "Instrumentation Engineer",
    "Sales Engineer",
    "Water Resources Engineer",
    "Urban Planning Engineer",
    "Solar Engineer",
    "Wind Engineer",
    "Engineering Manager",
    "Director of Engineering",
    "Vice President of Engineering",
  ],
  Developer: [
    "Front-End Developer",
    "Back-End Developer",
    "Full Stack Developer",
    "Web Developer",
    "Software Developer",
    "Mobile App Developer",
    "Game Developer",
    "DevOps Engineer",
    "Data Engineer",
    "UI/UX Developer",
    "Android Developer",
    "iOS Developer",
    "Embedded Systems Developer",
    "Graphics Developer",
    "Application Developer",
    "Database Developer",
    "Cloud Developer",
    "Security Developer",
    "System Developer",
    "Network Developer",
    "API Developer",
    "E-commerce Developer",
    "Python Developer",
    "Java Developer",
    "JavaScript Developer",
    "Ruby Developer",
    "PHP Developer",
    "C# Developer",
    "C++ Developer",
    "Scala Developer",
    "Go Developer",
    "Rust Developer",
    "Blockchain Developer",
    "AR/VR Developer",
    "Algorithm Developer",
    "Performance Engineer",
    "Quality Assurance Developer",
    "Software Architect",
    "Lead Developer",
    "Technical Lead",
    "Chief Technology Officer",
  ],
  Growth: [
    "Growth Hacker",
    "Growth Manager",
    "Data Analyst",
    "Performance Marketer",
    "Growth Product Manager",
    "SEO Strategist",
    "Conversion Rate Optimization Specialist",
    "Growth Engineer",
    "User Acquisition Specialist",
    "Content Strategist",
    "Digital Marketing Analyst",
    "Growth Marketing Manager",
    "Demand Generation Manager",
    "User Experience Analyst",
    "Web Analytics Specialist",
    "Social Media Growth Specialist",
    "Email Marketing Specialist",
    "Paid Acquisition Specialist",
    "Affiliate Marketing Manager",
    "Customer Retention Specialist",
    "Viral Marketing Manager",
    "Community Growth Manager",
    "Business Intelligence Analyst",
    "Product Analyst",
    "Funnel Optimization Specialist",
    "Lead Generation Specialist",
    "Marketing Automation Specialist",
    "Inbound Marketing Specialist",
    "Outbound Marketing Specialist",
    "Growth Team Lead",
    "Director of Growth",
    "VP of Growth",
    "Chief Growth Officer",
  ],
  Revenue: [
    "Revenue Manager",
    "Revenue Analyst",
    "Pricing Strategist",
    "Revenue Operations Manager",
    "Chief Revenue Officer",
    "Billing Manager",
    "Revenue Assurance Manager",
    "Revenue Cycle Manager",
    "Revenue Integrity Specialist",
    "Financial Planner",
    "Sales Analyst",
    "Business Revenue Analyst",
    "Revenue Optimization Specialist",
    "Monetization Strategist",
    "Revenue Forecasting Analyst",
    "Pricing Analyst",
    "Commercial Revenue Manager",
    "Revenue Recognition Specialist",
    "Revenue Product Manager",
    "Revenue Strategy Consultant",
    "Director of Revenue Management",
    "VP of Revenue",
    "Revenue Growth Analyst",
    "Revenue Performance Manager",
    "Sales and Revenue Planning Analyst",
    "Revenue Compliance Manager",
    "Account Revenue Specialist",
    "Revenue Reporting Analyst",
    "Market Revenue Manager",
    "Revenue Systems Analyst",
    "Revenue Cycle Auditor",
    "Director of Revenue Operations",
  ],
  Accounting: [
    "Accountant",
    "Accounting Clerk",
    "Auditor",
    "Accounting Manager",
    "Controller",
    "Financial Accountant",
    "Tax Accountant",
    "Bookkeeper",
    "Payroll Clerk",
    "Chief Financial Officer",
    "Accounts Payable Clerk",
    "Accounts Receivable Clerk",
    "Cost Accountant",
    "Management Accountant",
    "Forensic Accountant",
    "Public Accountant",
    "Certified Public Accountant",
    "Internal Auditor",
    "External Auditor",
    "Accounting Specialist",
    "Accounting Consultant",
    "Financial Reporting Manager",
    "Compliance Auditor",
    "Budget Analyst",
    "Credit Analyst",
    "Accounting Assistant",
    "Payroll Manager",
    "Payroll Administrator",
    "Inventory Accountant",
    "Fund Accountant",
    "Project Accountant",
    "Government Accountant",
    "Corporate Accountant",
    "Investment Accountant",
    "Operational Accountant",
    "Director of Accounting",
    "VP of Accounting",
    "Accounting Supervisor",
    "Accounting Officer",
    "Senior Accountant",
  ],
  Finance: [
    "Financial Analyst",
    "Finance Manager",
    "Investment Analyst",
    "Treasury Analyst",
    "Risk Manager",
    "Financial Planner",
    "Credit Analyst",
    "Finance Director",
    "Portfolio Manager",
    "Chief Financial Officer",
    "Corporate Finance Analyst",
    "Finance Consultant",
    "Financial Controller",
    "Finance Analyst",
    "Financial Advisor",
    "Budget Analyst",
    "Economic Analyst",
    "Finance Operations Manager",
    "Asset Manager",
    "Equity Research Analyst",
    "Quantitative Analyst",
    "Investor Relations Manager",
    "Mergers and Acquisitions Analyst",
    "Financial Risk Analyst",
    "Financial Project Manager",
    "Finance Product Manager",
    "Corporate Treasurer",
    "Finance Clerk",
    "Insurance Underwriter",
    "Pensions Manager",
    "Compliance Officer",
    "Financial Auditor",
    "Financial Reporting Manager",
    "Forensic Accountant",
    "Private Equity Analyst",
    "Venture Capital Analyst",
    "Funds Transfer Analyst",
    "Director of Finance",
    "Vice President of Finance",
    "Finance Supervisor",
  ],
  Healthcare: [
    "Registered Nurse",
    "Physician",
    "Surgeon",
    "Pharmacist",
    "Dental Hygienist",
    "Physical Therapist",
    "Radiologic Technologist",
    "Healthcare Administrator",
    "Medical Assistant",
    "Health Information Technician",
    "Clinical Laboratory Technician",
    "Occupational Therapist",
    "Speech-Language Pathologist",
    "Dentist",
    "Psychiatrist",
    "Clinical Research Coordinator",
    "Biomedical Engineer",
    "Public Health Officer",
    "Medical Secretary",
    "Dietitian",
    "Optometrist",
    "Chiropractor",
    "Podiatrist",
    "Anesthesiologist",
    "Paramedic",
    "Medical Billing Specialist",
    "Home Health Aide",
    "Nursing Assistant",
    "Caregiver",
    "Emergency Medical Technician",
    "Cardiologist",
    "Oncologist",
    "Neurologist",
    "Pediatrician",
    "Gynecologist",
    "Radiologist",
    "Endocrinologist",
    "Orthopedic Surgeon",
    "Urologist",
    "Dermatologist",
    "Psychologist",
    "Medical Director",
    "Chief Medical Officer",
  ],
  GeneralBusiness: [
    "Business Analyst",
    "Operations Manager",
    "Project Manager",
    "Product Manager",
    "Business Development Manager",
    "Account Manager",
    "Marketing Manager",
    "Sales Manager",
    "Human Resources Manager",
    "Financial Analyst",
    "Supply Chain Manager",
    "Logistics Manager",
    "Business Intelligence Analyst",
    "Compliance Officer",
    "Risk Manager",
    "Strategic Planner",
    "Corporate Strategy Manager",
    "Change Management Specialist",
    "Quality Assurance Manager",
    "Procurement Manager",
    "Customer Relations Manager",
    "Performance Improvement Manager",
    "Innovation Manager",
    "Sustainability Manager",
    "Corporate Social Responsibility Manager",
    "Business Operations Specialist",
    "Administrative Manager",
    "Executive Assistant",
    "Office Manager",
    "Public Relations Manager",
    "Business Consultant",
    "Management Consultant",
    "Director of Operations",
    "Vice President of Business Operations",
    "Chief Operations Officer",
  ],
  InformationTechnology: [
    "IT Support Specialist",
    "Systems Administrator",
    "Network Administrator",
    "Database Administrator",
    "IT Manager",
    "Security Analyst",
    "Systems Analyst",
    "Network Engineer",
    "Software Developer",
    "Web Developer",
    "Application Developer",
    "IT Project Manager",
    "Cloud Architect",
    "Data Scientist",
    "IT Director",
    "Chief Information Officer",
    "DevOps Engineer",
    "Cybersecurity Specialist",
    "Help Desk Technician",
    "User Experience Designer",
    "IT Consultant",
    "Business Systems Analyst",
    "Data Center Technician",
    "Infrastructure Engineer",
    "Cloud Systems Administrator",
    "Information Security Manager",
    "Network Security Engineer",
    "Software Quality Assurance Tester",
    "Mobile Application Developer",
    "Full Stack Developer",
    "Machine Learning Engineer",
    "IoT Developer",
    "Blockchain Developer",
    "IT Compliance Officer",
    "Technical Support Engineer",
    "IT Auditor",
    "Chief Technology Officer",
    "VP of Information Technology",
    "Information Systems Manager",
    "Technology Coordinator",
  ],
  Legal: [
    "Paralegal",
    "Legal Assistant",
    "Lawyer",
    "Attorney",
    "Legal Counsel",
    "Corporate Counsel",
    "Associate Attorney",
    "Litigation Attorney",
    "General Counsel",
    "Legal Secretary",
    "Compliance Officer",
    "Legal Analyst",
    "Contract Manager",
    "Patent Attorney",
    "Real Estate Attorney",
    "Family Law Attorney",
    "Immigration Attorney",
    "Labor Law Attorney",
    "Tax Attorney",
    "Intellectual Property Attorney",
    "Legal Advisor",
    "Chief Legal Officer",
    "Legal Consultant",
    "Environmental Law Attorney",
    "Criminal Defense Attorney",
    "Public Defender",
    "Prosecutor",
    "Legal Researcher",
    "Law Firm Administrator",
    "Judicial Clerk",
    "Court Reporter",
    "Mediator",
    "Arbitrator",
    "Legal Compliance Manager",
    "Document Review Attorney",
    "Legal Project Manager",
    "Legal Operations Manager",
    "Legal Technology Specialist",
    "Legal Marketing Manager",
    "Director of Legal Services",
  ],
  Education: [
    "Teacher",
    "Professor",
    "Lecturer",
    "School Counselor",
    "Educational Consultant",
    "Curriculum Developer",
    "School Administrator",
    "Principal",
    "Vice Principal",
    "Dean",
    "Academic Advisor",
    "Admissions Counselor",
    "Student Services Coordinator",
    "Librarian",
    "Special Education Teacher",
    "Teaching Assistant",
    "Research Assistant",
    "Coach",
    "Tutor",
    "Instructional Designer",
    "Education Program Manager",
    "Education Coordinator",
    "Childcare Director",
    "Preschool Teacher",
    "Elementary School Teacher",
    "High School Teacher",
    "Middle School Teacher",
    "Subject Matter Expert",
    "Career Counselor",
    "Education Technology Specialist",
    "Distance Learning Coordinator",
    "Educational Policy Maker",
    "School Psychologist",
    "School Nurse",
    "PE Teacher",
    "Art Teacher",
    "Music Teacher",
    "Foreign Language Teacher",
    "Science Teacher",
    "Mathematics Teacher",
    "Director of Education",
    "Chief Academic Officer",
  ],
  Creative: [
    "Graphic Designer",
    "Art Director",
    "Creative Director",
    "Copywriter",
    "Content Creator",
    "User Experience Designer",
    "User Interface Designer",
    "Web Designer",
    "Illustrator",
    "Animator",
    "3D Artist",
    "Video Editor",
    "Motion Graphics Designer",
    "Photographer",
    "Videographer",
    "Fashion Designer",
    "Interior Designer",
    "Set Designer",
    "Sound Engineer",
    "Music Producer",
    "Production Assistant",
    "Film Director",
    "Actor",
    "Dancer",
    "Choreographer",
    "Musician",
    "Composer",
    "Visual Merchandiser",
    "Event Planner",
    "Makeup Artist",
    "Hairstylist",
    "Costume Designer",
    "Advertising Designer",
    "Brand Strategist",
    "Creative Consultant",
    "Digital Media Specialist",
    "Print Designer",
    "Packaging Designer",
    "Typography Designer",
    "Concept Artist",
    "Art Curator",
    "Gallery Manager",
    "Creative Services Manager",
    "Scriptwriter",
    "Stage Manager",
    "Chief Creative Officer",
  ],
  Design: [
    "Graphic Designer",
    "UI/UX Designer",
    "Web Designer",
    "Product Designer",
    "Interior Designer",
    "Fashion Designer",
    "Industrial Designer",
    "Art Director",
    "Creative Director",
    "Visual Designer",
    "Motion Graphics Designer",
    "Animation Designer",
    "3D Designer",
    "Textile Designer",
    "CAD Designer",
    "Multimedia Designer",
    "Brand Designer",
    "Packaging Designer",
    "Digital Designer",
    "User Interface Developer",
    "User Experience Researcher",
    "Print Designer",
    "Layout Designer",
    "Concept Artist",
    "Illustrator",
    "Photography Director",
    "Typeface Designer",
    "Color Specialist",
    "Set Designer",
    "Exhibit Designer",
    "Environmental Designer",
    "Lighting Designer",
    "Storyboard Artist",
    "Jewelry Designer",
    "Tool Designer",
    "Display Designer",
    "Vehicle Designer",
    "Footwear Designer",
    "Costume Designer",
    "Chief Design Officer",
  ],
  Hospitality: [
    "Front Desk Clerk",
    "Concierge",
    "Housekeeper",
    "Room Service Attendant",
    "Bellhop",
    "Event Planner",
    "Banquet Manager",
    "Hotel Manager",
    "Resort Manager",
    "Guest Relations Manager",
    "Travel Coordinator",
    "Tour Guide",
    "Executive Chef",
    "Sous Chef",
    "Line Cook",
    "Bartender",
    "Waitstaff",
    "Host/Hostess",
    "Catering Manager",
    "Food and Beverage Manager",
    "Restaurant Manager",
    "Spa Manager",
    "Fitness Center Manager",
    "Casino Dealer",
    "Cruise Ship Attendant",
    "Club Manager",
    "Operations Manager",
    "Revenue Manager",
    "Sales Manager",
    "Marketing Manager",
    "Human Resources Manager",
    "Maintenance Technician",
    "Security Officer",
    "Valet",
    "Housekeeping Supervisor",
    "Executive Housekeeper",
    "Event Coordinator",
    "Meeting Planner",
    "Wedding Coordinator",
    "Front Office Manager",
    "General Manager",
    "Director of Hospitality",
    "Chief Hospitality Officer",
  ],
  Tourism: [
    "Tour Guide",
    "Travel Agent",
    "Tourism Manager",
    "Tour Operator",
    "Visitor Information Counsellor",
    "Tour Coordinator",
    "Travel Coordinator",
    "Destination Manager",
    "Event and Conference Organizer",
    "Heritage Officer",
    "Reservation Manager",
    "Tourism Marketing Manager",
    "Tourism Development Manager",
    "Travel Consultant",
    "Adventure Tourism Guide",
    "Cultural Tourism Coordinator",
    "Ecotourism Guide",
    "Hospitality Coordinator",
    "Leisure Travel Manager",
    "Tourism Promotion Specialist",
    "Tourist Information Manager",
    "Travel Blogger",
    "Travel Writer",
    "Tourism Researcher",
    "Tourism Policy Advisor",
    "Tourism Officer",
    "Tourism Project Manager",
    "Lifestyle Coordinator",
    "Recreation Coordinator",
    "Travel Public Relations Manager",
    "Eco-Tour Planner",
    "Tourism Education Specialist",
    "Tourism Safety Manager",
    "Tourism Consultant",
    "Director of Tourism",
    "Vice President of Tourism",
    "Chief Tourism Officer",
  ],
  Construction: [
    "Construction Worker",
    "Construction Manager",
    "Site Supervisor",
    "Project Manager",
    "Civil Engineer",
    "Structural Engineer",
    "Architect",
    "Quantity Surveyor",
    "Estimator",
    "Building Inspector",
    "Health and Safety Officer",
    "Foreman",
    "Site Engineer",
    "Construction Laborer",
    "Bricklayer",
    "Carpenter",
    "Electrician",
    "Plumber",
    "Roofer",
    "Painter",
    "Welder",
    "Heavy Equipment Operator",
    "Crane Operator",
    "Mason",
    "Concrete Finisher",
    "Surveyor",
    "Glazier",
    "Pipelayer",
    "Steel Erector",
    "Drywall Installer",
    "Flooring Installer",
    "Tiler",
    "HVAC Technician",
    "Demolition Worker",
    "Scaffolder",
    "Landscape Architect",
    "Project Coordinator",
    "Contracts Manager",
    "Procurement Officer",
    "Environmental Engineer",
    "Building Services Engineer",
    "Cost Engineer",
    "Construction Planner",
    "Construction Superintendent",
    "Construction Scheduler",
    "Director of Construction",
    "VP of Construction",
    "Chief Construction Officer",
  ],
  HumanResource: [
    "HR Generalist",
    "HR Manager",
    "HR Coordinator",
    "HR Specialist",
    "Recruiter",
    "Talent Acquisition Specialist",
    "HR Business Partner",
    "Compensation and Benefits Manager",
    "Employee Relations Specialist",
    "Training and Development Manager",
    "HR Analyst",
    "HR Administrator",
    "Payroll Specialist",
    "HR Consultant",
    "Talent Manager",
    "Labor Relations Specialist",
    "HR Assistant",
    "HR Compliance Manager",
    "HRIS Analyst",
    "Diversity and Inclusion Manager",
    "Organizational Development Specialist",
    "Chief Human Resources Officer (CHRO)",
    "VP of Human Resources",
    "HR Director",
    "Employee Engagement Specialist",
    "Learning and Development Specialist",
    "Benefits Administrator",
    "Recruitment Coordinator",
    "HR Operations Manager",
    "Workforce Planning Specialist",
    "Compensation Analyst",
    "Benefits Specialist",
    "HR Trainer",
    "Employee Wellness Coordinator",
    "Talent Development Manager",
    "Onboarding Specialist",
    "HR Project Manager",
    "HR Policy Analyst",
    "Human Capital Manager",
    "HR Communications Specialist",
  ],
};

module.exports = { jobRoles };
